spring.application.name=tareas-ad

# DATABASE CONFIGURACIÓN - MySQL para producción
spring.datasource.url=jdbc:mysql://localhost:3306/tareas_ad
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA CONFIGURACIÓN para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ACTIVE DIRECTORY / LDAP
app.ad.domain=parcial.tareas
spring.ldap.urls=ldap://192.168.1.41:389
spring.ldap.base=dc=parcial,dc=tareas
spring.ldap.username=cn=admin,dc=parcial,dc=tareas
spring.ldap.password=@Pass123
spring.ldap.connect.timeout=5000
spring.ldap.read.timeout=5000

# Security logs for troubleshooting login
logging.level.org.springframework.security=DEBUG
