spring.application.name=tareas-ad

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA CONFIGURATION
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# SERVER
server.port=8080

# ACTIVE DIRECTORY / LDAP
app.ad.domain=parcial.tareas
spring.ldap.urls=ldap://192.168.1.41:389
spring.ldap.base=dc=parcial,dc=tareas
spring.ldap.username=cn=admin,dc=parcial,dc=tareas
spring.ldap.password=@Password123
spring.ldap.connect.timeout=5000
spring.ldap.read.timeout=5000

# Security logs for troubleshooting login
logging.level.org.springframework.security=DEBUG
